apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: default  
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: default 
  labels:
    app: tomcat
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat 
    spec:
      containers:
        - name: tomcat
          image: rajgajjar/tomcat
          ports:
            - containerPort: 80
